#!/data/data/com.termux/files/usr/bin/bash

set -e

ROOT="$(git rev-parse --show-toplevel)"

echo "======================================"
echo " ADOS Project Generator"
echo "======================================"

mkdir -p "$ROOT/core/templates"

mkdir -p "$ROOT/core/templates/trading"

mkdir -p "$ROOT/core/templates/trading/backend"
mkdir -p "$ROOT/core/templates/trading/frontend"
mkdir -p "$ROOT/core/templates/trading/docs"
mkdir -p "$ROOT/core/templates/trading/tests"
mkdir -p "$ROOT/core/templates/trading/.github"

cat > "$ROOT/core/templates/trading/README.md" <<'DOC'
# Trading Project Template

Generated by ADOS.

This template is intended for projects such as:

- Aegis Trade Engine
- MT5 Automation
- Signal Engine
- Market Analyzer
DOC

cat > "$ROOT/core/templates/trading/AGENTS.md" <<'DOC'
# Project AI Rules

Always read:

MASTER_INDEX.md

ROADMAP.md

TODO.md

before implementing anything.
DOC

cat > "$ROOT/core/templates/trading/TODO.md" <<'DOC'
# Initial TODO

- Setup Backend
- Setup Frontend
- Setup Documentation
- Setup Testing
DOC

cat > "$ROOT/core/templates/trading/MASTER_INDEX.md" <<'DOC'
# Project Master Index

Status: Initial

Generated by ADOS.
DOC

echo
echo "Trading Template Installed."
echo
find "$ROOT/core/templates/trading" -maxdepth 2 | sort

