#!/data/data/com.termux/files/usr/bin/bash
set -e

ROOT="$(pwd)"

echo "========================================="
echo " ADOS STAGE-1 REPOSITORY PREPARATION"
echo "========================================="

if [ ! -d ".git" ]; then
    echo "Bukan root repository."
    exit 1
fi

echo
echo "[1/12] Membuat struktur utama"

mkdir -p \
constitution \
genome \
world \
contracts \
decision \
execution \
engine \
runtime \
handover \
memory \
state \
audit \
logs \
external \
external/repositories \
external/templates \
external/prompts \
external/benchmarks \
knowledge/raw \
knowledge/facts \
knowledge/patterns \
knowledge/rules \
knowledge/strategies \
knowledge/wisdom \
docs/architecture \
docs/specifications \
docs/rfc \
docs/adr \
scripts \
tests \
tools \
config

echo
echo "[2/12] Membuat README"

for d in \
constitution genome world contracts decision execution engine runtime \
handover memory state audit knowledge external docs specs
do

mkdir -p "$d"

cat > "$d/README.md" <<TXT
# $(basename $d)

Temporary placeholder.

Generated by bootstrap-stage1.
TXT

done

echo
echo "[3/12] gitkeep"

find constitution genome world contracts decision execution \
engine runtime handover memory state audit logs external \
knowledge docs tests tools config \
-type d \
-exec touch {}/.gitkeep \;

echo
echo "[4/12] Clone knowledge repository"

mkdir -p external/repositories

if [ ! -d external/repositories/open-source-ai-goldmine ]; then

git clone \
https://github.com/Moh4696/open-source-ai-goldmine.git \
external/repositories/open-source-ai-goldmine

else

echo "Sudah ada."

fi

echo
echo "[5/12] Context Loader"

cat > scripts/context-loader.py <<'PY'
from pathlib import Path

folders=[
"constitution",
"genome",
"world",
"contracts",
"knowledge",
"decision",
"execution",
"engine",
"runtime",
"handover",
"memory",
"state",
"docs",
"external/repositories"
]

print("="*60)

for f in folders:
    print(f,"OK" if Path(f).exists() else "MISSING")
PY

chmod +x scripts/context-loader.py

echo
echo "[6/12] Repository Scanner"

cat > scripts/scan.py <<'PY'
from pathlib import Path

required=[
"constitution",
"genome",
"world",
"contracts",
"knowledge",
"decision",
"execution",
"engine",
"runtime",
"handover",
"memory",
"state",
"docs",
"external"
]

missing=[]

for r in required:
    if not Path(r).exists():
        missing.append(r)

print("="*60)

if missing:
    print("Missing:")
    for i in missing:
        print("-",i)
else:
    print("Repository Healthy")

print("="*60)
PY

chmod +x scripts/scan.py

echo
echo "[7/12] Knowledge Manifest"

cat > knowledge/manifest.yaml <<YAML
version: 1

sources:

  repository:
    internal: ados-core

  external:
    - open-source-ai-goldmine

lifecycle:

  - raw
  - fact
  - validated
  - pattern
  - rule
  - strategy
  - wisdom
YAML

echo
echo "[8/12] Constitution"

cat > constitution/principles.md <<TXT
1. Repository adalah source of truth
2. Semua perubahan reversible
3. Semua keputusan berbasis evidence
4. Tidak overwrite external project
5. Semua AI wajib mengikuti constitution
TXT

echo
echo "[9/12] Genome"

cat > genome/genome.yaml <<YAML
immutable:
 - explainable
 - measurable
 - reversible
 - evidence_first
 - owner_control
YAML

echo
echo "[10/12] Git Status"

git status --short

echo
echo "[11/12] Scan"

python3 scripts/scan.py

echo
echo "[12/12] Context"

python3 scripts/context-loader.py

echo
echo "========================================="
echo "BOOTSTRAP COMPLETE"
echo "========================================="
